blog/urls.py
from django.conf.urls import include, url
from . import views

urlpatterns = [
	#url(r'^$', views.index, name='index'),
	# url(r'^register/$', views.register, name='register'),
	#url(r'^login/$', views.log_in, name='login'),
	#url(r'^my_(.*?)/$', views.my, name='my'),
	#url(r'^logout/$', views.log_out, name='logout'),
	url(r'^column/(?P<column_id>[0-9]+)/$', views.column, name='column'),
	url(r'^(?P<article_id>[0-9]+)/comment/$', views.comment, name='comment'),
	url(r'^(?P<article_id>[0-9]+)/keep/$', views.get_keep, name='keep'), 
	url(r'^(?P<article_id>[0-9]+)/poll/$', views.get_poll_article, name='poll'),
	url(r'^(?P<article_id>[0-9]+)/$', views.article, name='article'),

]

mall/urls.py
from django.conf.urls import include, url
from . import views

urlpatterns = [
	url(r'^shop_cart/$', views.shop_cart, name='shop_cart'),
	url(r'^mall_index/$',views.mall_index,name='mall_index'),
	url(r'^order_list/$',views.order_list,name='order_list'),
	url(r'^product_detail/(?P<product_id>[0-9]+)/$', views.product_detail, name='product_detail'),
	url(r'^order_detail/(?P<order_id>[0-9]+)/$', views.order_detail, name='order_detail'),
	url(r'^shop_cart_add/(?P<product_id>[0-9]+)/$', views.shop_cart_add, name='shop_cart_add'),
	url(r'^shop_cart_remove/(?P<pi_id>[0-9]+)/$',views.shop_cart_remove,name='shop_cart_remove'),
	url(r'^pay_detail/$',views.pay_detail,name='pay_detail'),
	url(r'^shop_quantity_plus/(?P<product_id>[0-9]+)/$', views.shop_quantity_plus, name='shop_quantity_plus'),
	url(r'^shop_quantity_minus/(?P<product_id>[0-9]+)/$', views.shop_quantity_minus, name='shop_quantity_minus'),
	url(r'^submit_order/(.*?)/$',views.submit_order,name='submit_order'),
	url(r'^submit_success/$',views.submit_success,name='submit_success'),

]

myblog/urls.py
from django.conf.urls import url,include
from django.contrib import admin
from django.contrib.auth import views as auth_views
from django.conf import settings
from django.conf.urls.static import static
urlpatterns = [
    	url(r'^admin/', admin.site.urls),
	url(r'^push/',include('push.urls')),
	url(r'^blog/',include('blog.urls')),
	url(r'^flow/',include('flow.urls')),
	url(r'^mall/',include('mall.urls')),
	url(r'^accounts/login/$', auth_views.login),
]+ static(settings.STATIC_URL, document_root = settings.STATIC_ROOT)

mall/models.py
# -*- coding: UTF-8 -*-
from __future__ import unicode_literals
from django.urls import reverse
from django.db import models
from django.contrib.auth.models import User
import sys
reload(sys)
sys.setdefaultencoding('utf-8')

class Category(models.Model):
	first_c  = models.CharField(verbose_name='一级分类',max_length=20)
	second_c = models.CharField(verbose_name='二级分类',max_length=20)
	three_c  = models.CharField(verbose_name='三级分类',max_length=20)
	
	def __unicode__(self):
		return u'%s-%s-%s' % (self.first_c,self.second_c,self.three_c)

class Product(models.Model):
	brand           = models.CharField(verbose_name='品牌',max_length=20)
	product_name    = models.CharField(verbose_name='商品名称',max_length=40)
	product_price   = models.IntegerField(verbose_name='价格')
	product_desc    = models.TextField(verbose_name='描述')
	create_date     = models.DateField(verbose_name='创建日期',auto_now_add=True)
	update_date     = models.DateField(verbose_name='更新日期',auto_now=True)
	inventory       = models.IntegerField(verbose_name='库存量')
	category        = models.ForeignKey(Category,verbose_name='商品类别')
	related_products=models.ManyToManyField('Product',null=True,blank=True,verbose_name='相关商品')
	
	def __unicode__(self):
		return self.product_name
		
	# def get_absolute_url(self):
		# return reverse('view_name',args=(self.id,))
class ProductItem(models.Model):
	product_name=models.ForeignKey(Product,verbose_name='商品')
	quantity    =models.IntegerField(default=1,verbose_name='商品数量')
	username    = models.ForeignKey(User,verbose_name='用户',null=True,on_delete=models.SET_NULL,related_name='product_user')
	def __unicode__(self):
		return self.product_name.product_name

class RegisterUser(models.Model):
	username     = models.ForeignKey(User,verbose_name='用户姓名',related_name='register_user')
	user_phone   = models.CharField(max_length=11,default='',verbose_name='手机号')
	user_address = models.TextField(verbose_name='地址')
	def __unicode__(self):
		return self.username.first_name

class Orders(models.Model):
	consumer         = models.ForeignKey(User,verbose_name='购买人',related_name='consumer_user')
	create_time      = models.DateTimeField(verbose_name='创建时间',auto_now_add=True)
	update_time      = models.DateTimeField(verbose_name='更新时间',auto_now=True)
	receiver         = models.CharField(verbose_name='收货人',max_length=20)
	receiver_phone   = models.CharField(max_length=11,default='',verbose_name='收货手机号')
	receiver_address = models.TextField(verbose_name='收货地址')
	amount           = models.IntegerField(verbose_name='订单总价')
	products         = models.ManyToManyField(ProductItem,verbose_name='商品')
	order_status     = models.IntegerField(verbose_name='订单状态')
	logistics        = models.IntegerField(verbose_name='运单号',null=True)
	
	# def get_absolute_url(self):
		# return reverse('view_name',args=(self.id,))

class ShoppingCart(models.Model):
	username    = models.ForeignKey(User,verbose_name='用户名',related_name='cart_user')
	products    = models.ManyToManyField(ProductItem,verbose_name='商品',null=True)
	create_date = models.DateField(verbose_name='创建日期',auto_now_add=True)
	update_date = models.DateField(verbose_name='更新日期',auto_now=True)
	
	# def get_absolute_url(self):
		# return reverse('view_name',args=(self.id,))

class ProductComment(models.Model):
	consumer    = models.ForeignKey(User,verbose_name='购买人',related_name='comment_user')
	product     = models.ForeignKey(Product,verbose_name='商品名')
	comment     = models.TextField(verbose_name='评价内容')
	create_time = models.DateTimeField(verbose_name='创建时间',auto_now_add=True)
	score       = models.IntegerField(verbose_name='评分')
	
	def __unicode__(self):
		return self.comment
	

push/views.py
# -*- coding: UTF-8 -*-
from django.shortcuts import render,render_to_response,redirect
from django.contrib.auth.models import User
from django.db.models import Q,F 
from django.contrib.auth import authenticate,login
from django.contrib.auth.decorators import login_required,permission_required
from django.contrib.auth import logout
from django.http import HttpResponse
from push.models import Push,AfterOpen,PushClick,PushActive,AreaActive,LossActive,UserList,AppOperate
from push.models import AppFunnel,AppBusiness,CarConversion
from push.models import Channel,AppKey,AppIndex,AppChart,AppDaily,LogList
from django.db.models import Avg,Sum,Count
from django.core import serializers
from django.views.generic.detail import DetailView
from django.views.generic.list import ListView
from push.forms import AfterOpenForm,LoginForm,AppActiveForm
from push.forms import PushForm,ModuleUserForm,DataCompareForm,CommunityConverForm
from push.forms import PushSendForm,PostDetailForm,RegisterForm,ForgetPasswordForm,ResetPasswordForm
from push.forms import AppStayForm,NewsDataForm,NewsRealForm,PostsRealForm,ChannelForm,AppIndexForm,AppIndexSingleForm,LogListForm
import json
from collections import OrderedDict
from django.core.paginator import Paginator,InvalidPage,EmptyPage,PageNotAnInteger
from datetime import datetime,date,timedelta
import csv 
from math import sqrt
from scipy.stats import ttest_ind
from scipy import stats
from sklearn import datasets, linear_model
import urllib
import urllib2
import logging
from django.core.mail import send_mail
from django.conf import settings
import hashlib
import sys
reload(sys)
sys.setdefaultencoding('utf-8')
# Author.objects.values('name').annotate(average_rating=Avg('book__rating'))
# Create your views here.
from django.views.generic.edit import CreateView,UpdateView,DeleteView
from push.models import UserList
from django.core.urlresolvers import reverse_lazy
class UserListList(ListView):
	model=UserList
class UserListDetail(DetailView):
	model=UserList
class UserCreate(CreateView):
	model=UserList
	fields=['username','password']
	success_url = '/push/userlist/'
class UserUpdate(UpdateView):
	model=UserList
	fields=['username','password']
	success_url = '/push/userlist/'
	template_name_suffix = '_update_form'
class UserDelete(DeleteView):
	model=UserList
	success_url = reverse_lazy('userlist')

def str2md5(username,email):
	str=username+email[::-1]
	md5 = hashlib.md5()
	md5.update(str.encode('utf-8'))
	str_md5=md5.hexdigest()
	return str_md5

def push_login(request):
	if request.method =='GET':
		form=LoginForm()
		register_msg='没有账号？立即注册！'
		return render(request,'push_login.htm', {'form': form,'register_msg':register_msg})
	elif request.method=='POST':
		form=LoginForm(request.POST)
		if form.is_valid():
			username = form.cleaned_data['username']
			password = form.cleaned_data['password']
			try:
				user=User.objects.get(username=username)
			except User.DoesNotExist:
				register_msg='没有账号？立即注册！'
				return render(request,'push_login.htm', {'form': form,'register_msg':register_msg})
			user = authenticate(username=username, password=password)
			if user is None:
				forget_msg='忘记密码'
				return render(request,'push_login.htm', {'form': form,'forget_msg':forget_msg})
			else:
				if user.is_active:
					login(request, user)
					return redirect('/push/app_active/')

		else:
			form=LoginForm()
			msg='账号或密码错误'
			return render(request,'push_login.htm', {'form': form,'msg':msg})


def logout_view(request):
	logout(request)
	form=LoginForm()
	return redirect('/push/push_login/')


def register(request):
	if request.method == 'GET':
		form= RegisterForm()
		return render(request,'register.htm',{'form':form})
	elif request.method == 'POST':
		form= RegisterForm(request.POST)
		if form.is_valid():
			username=form.cleaned_data['username']
			email=form.cleaned_data['email']
			password=form.cleaned_data['password']
			user = User.objects.create_user(username,email,password)
			user.save()
			return redirect('/push/push_login/')
			
def forget_password(request):
	if request.method =='GET':
		form=ForgetPasswordForm()
		return render(request,'forget_password.htm',{'form':form})
	elif request.method =='POST':
		form=ForgetPasswordForm(request.POST)
		if form.is_valid():	
			username=form.cleaned_data['username']
			email=form.cleaned_data['email']
			init_email=User.objects.filter(username=username).values('email')
			init_email=list(init_email)[0]['email']
			if email !=init_email:
				msg='邮箱和注册邮箱不符，请重新输入！'
				return render(request,'forget_password.htm',{'form':form,'msg':msg})
			emails=[]
			emails.append(form.cleaned_data['email'])
			encrypt=str2md5(username,email)
			url='http://172.20.4.64:8000/push/reset_password/'+encrypt+'/'
			send_mail('重置密码',url,settings.DEFAULT_FROM_EMAIL,emails,fail_silently=False)
			msg='密码重置链接已发至您的邮箱!'
			res=render(request,'forget_password.htm',{'form':form,'msg':msg})
			res.set_cookie("reset_username",username)
			res.set_cookie("reset_email",email)
			return res
		else:
			msg='用户名或邮箱输入错误，请重新输入！'
			return render(request,'forget_password.htm',{'form':form,'msg':msg})
	
def reset_password(request,encrypt):
	if request.method == 'GET':
		form= ResetPasswordForm()
		return render(request,'reset_success.htm',{'form':form})
	elif request.method == 'POST':
		form= ResetPasswordForm(request.POST)
		if form.is_valid():
			new_password=form.cleaned_data['password']
			username=request.COOKIES.get("reset_username")
			email=request.COOKIES.get("reset_email")
			if str2md5(username,email)==encrypt:
				u = User.objects.get(username=username)
				u.set_password(new_password)
				u.save()
				msg='密码重置成功!'
				url='立即登录'
				return render(request,'reset_success.htm',{'form':form,'msg':msg,'url':url})
			else:
				msg='错误的链接!'
				return render(request,'reset_success.htm',{'form':form,'msg':msg})

def loglist_create(request):
	if request.method == 'GET':
		form= LogListForm()
		return render(request,'loglist_create.htm',{'form':form})
	elif request.method == 'POST':
		form= LogListForm(request.POST)
		if form.is_valid():
			version=form.cleaned_data['version']
			type_desc=form.cleaned_data['type_desc']
			type_name=form.cleaned_data['type_name']
			page_name=form.cleaned_data['page_name']
			column_name=form.cleaned_data['column_name']
			section_name=form.cleaned_data['section_name']
			view_name=form.cleaned_data['view_name']
			object_name=form.cleaned_data['object_name']
			object_id=form.cleaned_data['object_id']
			obj=LogList(version=version,
						type_desc=type_desc,
						type_name=type_name,
						page_name=page_name,
						column_name=column_name,
						section_name=section_name,
						view_name=view_name,
						object_name=object_name,
						object_id=object_id)
			obj.save()

logger = logging.getLogger('browse')
def get_newsdetail(page=1):
    url='http://api.ycapp.yiche.com/appnews/TouTiaoV64'
    values={}
    values['page'] = page
    data = urllib.urlencode(values)
    geturl = url + "?"+data
    request = urllib2.Request(geturl)
    response = urllib2.urlopen(request)
    js=json.loads(response.read())
    return js['data']['list']

now=datetime.now()
start_init=now-timedelta(days=7)
end_init  =now-timedelta(days=1)
day_before=end_init-timedelta(days=1)
week_before=end_init-timedelta(days=7)
month_before=end_init-timedelta(days=30)
def day_start(end_init):
	return end_init-timedelta(days=1)

def week_start(end_init):
	num=end_init.weekday()
	return end_init-timedelta(days=num+7)
	
	
def month_start(end_init):
	year=end_init.year
	month=end_init.month
	
	if month==1:
		year=year-1
		month=12
	else:
		month=month-1
	return datetime(year,month,1)
	
def field_label(value):
	return {'new_adr':'adr新增','new_ios':'ios新增','new_app':'app新增','active_adr':'adr活跃','active_ios':'ios活跃','active_app':'app活跃',\
	'video_adr':'adr视频播放','video_ios':'ios视频播放','video_app':'app视频播放','login_adr':'adr登录','login_ios':'ios登录','login_app':'app登录',\
	'headline_user':'头条用户数','community_user':'社区用户数','selectcar_user':'选车用户数','service_user':'服务用户数','headline_read':'头条阅读量','headline_photo':'组图阅读量',\
	'news_add':'新增资讯','news_avg':'平均阅读资讯数','reply_add':'新增评论','like_add':'新增点赞','news_share':'文章分享','sharepage_click':'分享页点击数',\
	'community_posts':'社区发帖数','topic_posts':'主题帖','question_posts':'提问帖','vote_posts':'投票贴','bycar_posts':'提车作业','replies':'回帖数',\
	'likes':'点赞数','interactives':'互动数','attentions':'关注数'}[value]
	

def tran_keys(key_list):
	tp_list=[]
	temp_data=AppKey.objects.all().values('c_key','c_desc')
	you_dict={}
	for item in temp_data:
		you_dict[item['c_key']]=item['c_desc']
	for item in key_list:
		tp_list.append(you_dict[item])
	return tp_list
		
def multipl(a,b):
	sumofab=0.0
	for i in range(len(a)):
		temp=a[i]*b[i]
		sumofab+=temp
	return sumofab
 
def correlation(x,y):
	n=len(x)
	sum1=sum(x)
	sum2=sum(y)
	sumofxy=multipl(x,y)
	sumofx2 = sum([pow(i,2) for i in x])
	sumofy2 = sum([pow(j,2) for j in y])
	num=sumofxy-(float(sum1)*float(sum2)/n)
	den=sqrt((sumofx2-float(sum1**2)/n)*(sumofy2-float(sum2**2)/n))
	return num/den


def core_indicator(object):
	index_dict=serializers.serialize("json", object.objects.filter(date__gte=week_before.strftime('%Y-%m-%d'),date__lte=end_init.strftime('%Y-%m-%d')))
	index_dict=list(map(lambda x:x['fields'],json.loads(index_dict)))
	field_list=[]
	for _ in index_dict[0]:
		if _ not in ['date','week','month']:
			field_list.append(_)
	for item in index_dict:
		if item['date']==end_init.strftime('%Y-%m-%d'):
			last_day_dict={}
			for unit in field_list:
				last_day_dict['last_day_'+unit]=item[unit]

	for item in index_dict:
		if item['date']==day_before.strftime('%Y-%m-%d'):
			day_before_dict={}
			for unit in field_list:
				day_before_dict['day_before_'+unit]='%.2f'%(100*(float(last_day_dict['last_day_'+unit])/item[unit]-1))+'%'

	for item in index_dict:
		if item['date']==week_before.strftime('%Y-%m-%d'):
			week_before_dict={}
			for unit in field_list:

mall/templates/index.html
<form action="" method="post">
{% csrf_token %}
{{ form.as_p }}
<input type="submit" value="提交" />
</form>

<form action="" method="post">
{% for checkbox in form.products %}
<p>
<label for="{{ checkbox.id_for_label }}">
<span class="checkbox">{{ checkbox.tag }}</span>
{{ checkbox.choice_label }}
</label>
</p>
{% endfor %}
<input type="submit" value="提交" />
</form>

mall/templates/mall_head.html
{% include "flow_index.html" %}

<form action="/mall/mall_index/" method="post">
 {% csrf_token %}
<input id="search"  type="text" name="search"/>
<button type="submit" class="btn btn-danger">搜索</button>
<a href="{% url 'shop_cart'  %}"><span class="glyphicon glyphicon-shopping-cart"></span>我的购物车{{goods}}</a>
<a href="{% url 'order_list'  %}">我的订单</a>
</form>

mall/templates/mall_index.html
{% include "mall_head.html" %}



{% for product in product_list %}
<p>
<a href="{% url 'product_detail' product.id %}">{{product.product_name}}</a>
</p>
{% endfor %}

mall/templates/old_index.html
<form action="" method="post">
{% csrf_token %}
{{ form.as_p }}
<input type="submit" value="提交" />
</form>

mall/templates/old_index2.html
<form action="" method="post">
<table class="table table-bordered table-hover table-responsive table-striped">
<thead>
<tr><th>全选</th><th>商品</th><th>单价</th><th>数量</th><th>小计</th></tr>
</thead>
{% for product in product_list %}
<tr>
<td><input id="id_products_{{product.id}}" name="products" type="checkbox" value="{{product.id}}" /></td>
<td>{{ product.product_name.product_name}}</td>
<td>￥{{ product.product_name.product_price}}</td>
<td>{{ product.quantity}}</td>
<td>￥{% widthratio product.product_name.product_price 1 product.quantity%}</td>
</tr>
{% endfor %}
</table>
<input type="submit" value="提交" />
</form>
{{product_data}}

mall/templates/old_mall_index.html
{% include "flow_index.html" %}


<form action="" method="post">
 {% csrf_token %}
<input id="search"  type="text" name="search"/>
<button type="submit" class="btn btn-danger">搜索</button>
<a href="{% url 'shop_cart'  %}"><span class="glyphicon glyphicon-shopping-cart"></a>
</form>

{% for product in product_list %}
<p>
<a href="{% url 'product_detail' product.id %}">{{product.product_name}}</a>
</p>
{% endfor %}

mall/templates/old_product_detail.html
{% include "mall_head.html" %}

{{product_items.id}}
<p>商品品牌：{{product_detail.brand}}</p>
<p>商品名：{{product_detail.product_name}}</p>
<p>价格：{{product_detail.product_price}}</p>
<p>描述：{{product_detail.product_desc}}</p>
<a href="{% url 'submit_order' product_items.id %}"><button type="submit" class="btn btn-danger">立即购买</button></a>
<a href="{% url 'shop_cart_add' product_detail.id %}"><button type="submit" class="btn btn-success">加入购物车</button></a>

mall/templates/old_shop_cart.html
{% include "flow_index.html" %}


<form action="" method="post">
 {% csrf_token %}
<table class="table table-bordered table-hover table-responsive table-striped">
<thead>
<tr><th><input id="id_products"  type="checkbox" />全选</th>
<th>商品</th><th>单价</th><th>数量</th><th>小计</th></tr>
</thead>
{% for product in product_list %}
<tr>
<td><input id="id_products_{{product.id}}" name="products" type="checkbox" value="{{product.id}}" /></td>
<td><a href="{% url 'product_detail' product.product_name.id %}">{{ product.product_name.product_name}}</a></td>
<td>￥{{ product.product_name.product_price}}</td>
<td><span class="glyphicon glyphicon-minus"></span>&nbsp{{ product.quantity}}&nbsp<span class="glyphicon glyphicon-plus"></span></td>
<td>￥{% widthratio product.product_name.product_price 1 product.quantity%}</td>
</tr>
{% endfor %}
</table>
<!-- <input type="submit" value="去结算" /> -->
<button type="submit" class="btn btn-danger">去结算</button>
</form>

{{product_data}}

mall/templates/order_detail.html
{% include "mall_head.html" %}


<p>下单用户：{{order_detail.consumer}}</p>
<p>订单金额：{{order_detail.amount}}</p>
<p>收货人：  {{order_detail.receiver}}</p>
<p>收货地址：{{order_detail.receiver_address}}</p>

mall/templates/order_list.html
{% include "mall_head.html" %}

<table class="table table-bordered table-hover table-responsive table-striped">
<thead>
<tr><th>订单号</th><th>下单用户</th><th>订单金额</th><th>收货人</th></tr>
</thead>
{% for order in order_list %}
<tr>
<td><a href="{% url 'order_detail' order.id %}">{{ order.id}}</a></td>
<td>{{ order.consumer.first_name}}</td>
<td>{{ order.amount}}</td>
<td>{{order.receiver}}</td>
</tr>
{% endfor %}
</table>

mall/templates/product_detail.html
{% include "mall_head.html" %}


<p>商品品牌：{{product_detail.brand}}</p>
<p>商品名：{{product_detail.product_name}}</p>
<p>价格：{{product_detail.product_price}}</p>
<p>描述：{{product_detail.product_desc}}</p>
<a href="{% url 'submit_order' product_items.id %}"><button type="submit" class="btn btn-danger">立即购买</button></a>
<a href="{% url 'shop_cart_add' product_detail.id %}"><button type="submit" class="btn btn-success">加入购物车</button></a>

mall/templates/shop_cart.html
{% include "mall_head.html" %}


<form action="" method="post">
 {% csrf_token %}
<table class="table table-bordered table-hover table-responsive table-striped">
<thead>
<tr><th><input id="id_products"  type="checkbox" />全选</th>
<th>商品</th><th>单价</th><th>数量</th><th>小计</th></tr>
</thead>
{% for product in product_list %}
<tr>
<td><input id="id_products_{{product.id}}" name="products" type="checkbox" value="{{product.id}}" /></td>
<td><a href="{% url 'product_detail' product.product_name.id %}">{{ product.product_name.product_name}}</a></td>
<td>￥{{ product.product_name.product_price}}</td>
<td>
<a href="{% url 'shop_quantity_minus' product.product_name.id %}"><span class="glyphicon glyphicon-minus"></span></a>
&nbsp
{{ product.quantity}}
&nbsp
<a href="{% url 'shop_quantity_plus' product.product_name.id %}"><span class="glyphicon glyphicon-plus"></span></a></td>
<td>￥{% widthratio product.product_name.product_price 1 product.quantity%}
<a href="{% url 'shop_cart_remove' product.id %}">移除</a>
</td>
</tr>
{% endfor %}
</table>
<!-- <input type="submit" value="去结算" /> -->
<button type="submit" class="btn btn-danger">去结算</button>
</form>

{{product_data}}

mall/templates/submit_order.html
{% include "flow_index.html" %}

<table class="table table-bordered table-hover table-responsive table-striped">
<thead>
<tr><th>商品</th><th>单价</th><th>数量</th><th>小计</th></tr>
</thead>
{% for product in product_items %}
<tr>
<td><a href="{% url 'product_detail' product.product_name.id %}">{{ product.product_name.product_name}}</a></td>
<td>￥{{ product.product_name.product_price}}</td>
<td>{{ product.quantity}}</td>
<td>￥{% widthratio product.product_name.product_price 1 product.quantity%}</td>
</tr>
{% endfor %}
</table>
<form action="" method="post">
 {% csrf_token %}
{{form.as_p}}

<button type="submit" class="btn btn-danger">提交订单</button>
</form>

{{product_data}}